/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BookRequest {
  authorName: string;
  isbn: string;
  id?: number;
  shareable?: boolean;
  synopsis: string;
  tittle: string;
}
